### ISSUE TITLE
Enable app functionalities with sample data

### ISSUE THREAD

**Issue by xni7** [SafetyGraphics/volcano-plot#16]
- document sample data
- enable other functionalities with sample data
- look into other sample data
    + CTSPEDIA
    + Jim's data

Phuse xanomeline sample data

---
    adae <- haven::read_xpt("https://github.com/phuse-org/phuse-scripts/raw/master/data/adam/cdisc/adae.xpt") 
    adsl <- haven::read_xpt("https://github.com/phuse-org/phuse-scripts/raw/master/data/adam/cdisc/adsl.xpt") 
---

**Comment by isaaczhao-alk** [comment]
Thanks for the sample dataset to get started Xiao! It looks like many of the variable names need to be re-mapped in order to work with the functions for now
