### ISSUE TITLE
Finish P-value adjustment function.

### ISSUE THREAD

**Issue by xni7** [SafetyGraphics/volcano-plot#9]

**Comment by isaaczhao-alk** [comment]
Does the adjusted vs. unadjusted option not work?
Can just used p.adjust(x, method="BH")

![image](https://user-images.githubusercontent.com/62663896/84848804-d7d9b580-b021-11ea-9fb6-1f15535c8d03.png)

**Comment by isaaczhao-alk** [comment]
Adjusted p-value is FDR correction. y-axis labels are changed to adjusted p value values.
